### ISSUE TITLE
Issue in case of replace

### ISSUE THREAD

**Issue by rahul38888** [xlwings/jsondiff#59]
```
a = {1:2}
b = {5:3}
diff(a,b,syntax="explicit")
```

The output in the above scenario is `{5:3}` rather than `{$replace: {5: 3}}` or `{$insert: {5: 3}, $delete: {1:2}}`, which I think a better way in case of `explicit`

**Comment by 0xquad** [comment]
Looks like a bug to me as well. See my comment in #36 which is the same issue.

That said, this project is not very much alive; many of the newer issues in the last 3-5 years haven't really been addressed by the maintainer. There are forks, but they are not up to date with the latest commits from this project. That's too bad because this simple library is pretty useful and I haven't found any other good ones so far, so we have to live with those bugs for now.

**Comment by fzumstein** [comment]
closed by #64
